--seleciona os alunos e seus cursos
SELECT
    a.NOME AS ALUNO,
    c.NOME AS CURSO
FROM ALUNO a
JOIN CURSO_ALUNOS ca ON ca.CODALUNO = a.CODALUNO
JOIN CURSO c ON c.CODCURSO = ca.CODCURSO
ORDER BY a.NOME, c.NOME;

--seleciona o curso e quantidade de alunos
SELECT
    c.NOME AS CURSO,
    COUNT(ca.CODALUNO) AS QTDE_ALUNOS
FROM CURSO c
LEFT JOIN CURSO_ALUNOS ca ON ca.CODCURSO = c.CODCURSO
GROUP BY c.CODCURSO, c.NOME
ORDER BY QTDE_ALUNOS DESC;

--seleciona os professoes e suas materias
SELECT
    p.NOME AS PROFESSOR,
    m.NOME AS MATERIA
FROM PROFESSOR p
JOIN MATERIAS_PROFESSORES mp ON mp.CODPROFESSOR = p.CODPROFESSOR
JOIN MATERIAS m ON m.CODMATERIA = mp.CODMATERIA
ORDER BY p.NOME, m.NOME;

-- seleciona matérias do curso, junto do professor responsável
SELECT
    c.NOME AS CURSO,
    m.NOME AS MATERIA,
    p.NOME AS PROFESSOR
FROM CURSO c
JOIN CURSO_MATERIAS cm ON cm.CODCURSO = c.CODCURSO
JOIN MATERIAS m ON m.CODMATERIA = cm.CODMATERIA
LEFT JOIN MATERIAS_PROFESSORES mp ON mp.CODMATERIA = m.CODMATERIA
LEFT JOIN PROFESSOR p ON p.CODPROFESSOR = mp.CODPROFESSOR
WHERE c.CODCURSO = :CODCURSO
ORDER BY c.NOME, m.NOME;


--busca contato do aluno
SELECT
    a.NOME AS ALUNO,
    ac.TIPO_CONTATO,
    ac.CONTATO
FROM ALUNO a
LEFT JOIN ALUNOS_CONTATOS ac ON ac.CODALUNO = a.CODALUNO
WHERE a.CODALUNO = :codaluno